/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AppModelService } from "../appModel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AppModelCreateInput } from "./AppModelCreateInput";
import { AppModel } from "./AppModel";
import { AppModelFindManyArgs } from "./AppModelFindManyArgs";
import { AppModelWhereUniqueInput } from "./AppModelWhereUniqueInput";
import { AppModelUpdateInput } from "./AppModelUpdateInput";
import { UserAppAccessFindManyArgs } from "../../userAppAccess/base/UserAppAccessFindManyArgs";
import { UserAppAccess } from "../../userAppAccess/base/UserAppAccess";
import { UserAppAccessWhereUniqueInput } from "../../userAppAccess/base/UserAppAccessWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AppModelControllerBase {
  constructor(
    protected readonly service: AppModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AppModel })
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAppModel(
    @common.Body() data: AppModelCreateInput
  ): Promise<AppModel> {
    return await this.service.createAppModel({
      data: data,
      select: {
        cookies: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AppModel] })
  @ApiNestedQuery(AppModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appModels(@common.Req() request: Request): Promise<AppModel[]> {
    const args = plainToClass(AppModelFindManyArgs, request.query);
    return this.service.appModels({
      ...args,
      select: {
        cookies: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AppModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appModel(
    @common.Param() params: AppModelWhereUniqueInput
  ): Promise<AppModel | null> {
    const result = await this.service.appModel({
      where: params,
      select: {
        cookies: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AppModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAppModel(
    @common.Param() params: AppModelWhereUniqueInput,
    @common.Body() data: AppModelUpdateInput
  ): Promise<AppModel | null> {
    try {
      return await this.service.updateAppModel({
        where: params,
        data: data,
        select: {
          cookies: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AppModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAppModel(
    @common.Param() params: AppModelWhereUniqueInput
  ): Promise<AppModel | null> {
    try {
      return await this.service.deleteAppModel({
        where: params,
        select: {
          cookies: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/userAppAccesses")
  @ApiNestedQuery(UserAppAccessFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserAppAccess",
    action: "read",
    possession: "any",
  })
  async findUserAppAccesses(
    @common.Req() request: Request,
    @common.Param() params: AppModelWhereUniqueInput
  ): Promise<UserAppAccess[]> {
    const query = plainToClass(UserAppAccessFindManyArgs, request.query);
    const results = await this.service.findUserAppAccesses(params.id, {
      ...query,
      select: {
        appField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userAppAccesses")
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "update",
    possession: "any",
  })
  async connectUserAppAccesses(
    @common.Param() params: AppModelWhereUniqueInput,
    @common.Body() body: UserAppAccessWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAppAccesses: {
        connect: body,
      },
    };
    await this.service.updateAppModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userAppAccesses")
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "update",
    possession: "any",
  })
  async updateUserAppAccesses(
    @common.Param() params: AppModelWhereUniqueInput,
    @common.Body() body: UserAppAccessWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAppAccesses: {
        set: body,
      },
    };
    await this.service.updateAppModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userAppAccesses")
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "update",
    possession: "any",
  })
  async disconnectUserAppAccesses(
    @common.Param() params: AppModelWhereUniqueInput,
    @common.Body() body: UserAppAccessWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAppAccesses: {
        disconnect: body,
      },
    };
    await this.service.updateAppModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/fetch-cookies/:appId")
  @swagger.ApiOkResponse({
    type: AppModelUpdateInput,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async FetchCookies(
    @common.Body()
    body: AppModelUpdateInput
  ): Promise<AppModelUpdateInput> {
    return this.service.FetchCookies(body);
  }

  @common.Post("/update-cookies/:appId")
  @swagger.ApiOkResponse({
    type: AppModelUpdateInput,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async UpdateCookies(
    @common.Body()
    body: AppModelUpdateInput
  ): Promise<AppModelUpdateInput> {
    return this.service.UpdateCookies(body);
  }
}
